/* Written by SD Asif Hossein, released under GPL-3 license. */

module alu_decoder(
    input  logic [1:0] alu_op,
    input  logic [2:0] funct3,
    input  logic [6:0] funct7,
    input  logic [6:0] opcode,

    /* What kind of ALU operation do we need. */
    output logic [2:0] alu_control
);
    /* ALU operations used by this processor (ALU Control). */
    localparam logic [2:0] ALU_ADD = 3'b000;
    localparam logic [2:0] ALU_SUB = 3'b001;
    localparam logic [2:0] ALU_AND = 3'b010;
    localparam logic [2:0] ALU_OR  = 3'b011;
    localparam logic [2:0] ALU_SLT = 3'b101;

    /* ALU operation categories generated by the main decoder. */
    localparam logic [1:0] ALUOP_ADD      = 2'b00;
    localparam logic [1:0] ALUOP_BRANCH   = 2'b01;
    localparam logic [1:0] ALUOP_FUNCTION = 2'b10;

    always @* begin
        /* Default to ADD so that every input combination has a
          defined and safe ALU control value. */
        alu_control = ALU_ADD;

        case(alu_op)
            /* LOAD and STORE instructions need the ALU to
              calculate an address: base register + immediate. */
            ALUOP_ADD: begin
                alu_control = ALU_ADD;
            end

            /* Branch instructions use subtraction to compare values. Wild. */
            ALUOP_BRANCH: begin
                alu_control = ALU_SUB;
            end

            /* r-type and i-type ALU instructions require funct3
              and, for some instructions, funct7/opcode bits. */
            ALUOP_FUNCTION: begin
                case(funct3)
                    /* ADD, SUB and ADDI */
                    3'b000: begin
                        if({opcode[5], funct7[5]} == 2'b11)  /* glue check */
                            alu_control = ALU_SUB;
                        else
                            alu_control = ALU_ADD;
                    end

                    /* SLT */
                    3'b010: begin
                        alu_control = ALU_SLT;
                    end

                    /* OR */
                    3'b110: begin
                        alu_control = ALU_OR;
                    end

                    /* AND */
                    3'b111: begin
                        alu_control = ALU_AND;
                    end

                    /* Unsupported funct3 value. */
                    default: begin
                        alu_control = ALU_ADD;
                    end
                endcase
            end

            /* Unsupported ALU control. */
            default: begin
                alu_control = ALU_ADD;
            end
        endcase
    end

endmodule
